# Generated by Django 6.1.1 on 2026-10-05 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('rent', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('amenity', models.CharField(max_length=240)),
                ('kind', models.CharField(max_length=60)),
                ('verified', models.BooleanField(default=False)),
                ('vacant', models.BooleanField(default=True)),
                ('image', models.URLField(max_length=500)),
                ('image_alt', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='api.estate')),
            ],
            options={
                'ordering': ['rent', 'title'],
            },
        ),
    ]
