const properties = [
  {
    id: 'kilimani-garden-apartment',
    title: 'Garden-view apartment',
    location: 'Kilimani',
    city: 'Nairobi',
    rent: 68000,
    bedrooms: 2,
    amenity: 'Lift · 24/7 security',
    kind: 'Apartment',
    verified: true,
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=85',
    imageAlt: 'Bright modern apartment opening onto a garden terrace',
  },
  {
    id: 'westlands-city-apartment',
    title: 'Sunlit city apartment',
    location: 'Westlands',
    city: 'Nairobi',
    rent: 95000,
    bedrooms: 2,
    amenity: 'Pool · Backup power',
    kind: 'Apartment',
    verified: true,
    image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=85',
    imageAlt: 'Contemporary neutral living room with wide windows',
  },
  {
    id: 'kileleshwa-family-home',
    title: 'Quiet family residence',
    location: 'Kileleshwa',
    city: 'Nairobi',
    rent: 118000,
    bedrooms: 3,
    amenity: 'Garden · Parking',
    kind: 'Townhouse',
    verified: true,
    image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=85',
    imageAlt: 'Modern family home with a leafy outdoor area',
  },
  {
    id: 'ruiru-courtyard-home',
    title: 'Courtyard maisonette',
    location: 'Ruiru',
    city: 'Kiambu',
    rent: 52000,
    bedrooms: 3,
    amenity: 'Gated estate · Parking',
    kind: 'Maisonette',
    verified: true,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85',
    imageAlt: 'Modern two-storey house with landscaped front garden',
  },
  {
    id: 'karen-green-home',
    title: 'Green garden bungalow',
    location: 'Karen',
    city: 'Nairobi',
    rent: 145000,
    bedrooms: 3,
    amenity: 'Garden · Pet friendly',
    kind: 'Bungalow',
    verified: true,
    image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1000&q=85',
    imageAlt: 'Spacious home set among mature trees',
  },
  {
    id: 'nyali-coastal-flat',
    title: 'Coastal breeze flat',
    location: 'Nyali',
    city: 'Mombasa',
    rent: 48000,
    bedrooms: 1,
    amenity: 'Balcony · Water included',
    kind: 'Apartment',
    verified: true,
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=85',
    imageAlt: 'Airy coastal apartment interior in warm natural light',
  },
]

export default properties